### ISSUE TITLE
cannot find PADS class for void launchControllerPadChanged(PADS pad)

### ISSUE THREAD

**Issue by dborowik** [haschdl/pLaunchPadMini#2]
Thank you for putting the library together. I am trying to use 
`void launchControllerPadChanged(PADS pad)`
to get the location of a pressed pad but Processing correctly points to PADS class not defined.

Could you please add an example on how to use it, or shall I create a PADS class based on your LaunchPad library which does includes it? or, could you please tell me the best to find which pad is pressed using your library? I could check all pads status every time of course, but it seems rather long-winded.

Thanks for your help!

**Comment by haschdl** [comment]
hello @dborowik ! Here is a minimal example that I just tested. Does it work for you? 

``` java
import pLaunchController.*;
LaunchController controller;

void setup() {
  size(1000, 500);

  try {
    controller = new LaunchController(this);
  }
  catch(Exception e) {
    println("Unfortunately we could not detect that Launch Control is connected to this computer :(");
  }
}

void launchControllerPadChanged(PADS pad) {
  print(pad);
}
```

**Comment by haschdl** [comment]
From the example above, every time I press a pad, I get on the console:
`PAD_1`
or
`PAD_2`

**Comment by haschdl** [comment]
Hi @dborowik  just to make sure, which device you are using? This library (in this repo) was intended for the Launch Pad Mini, and I have another Launch Control. 

This library:
https://github.com/haschdl/pLaunchPadMini

Other library:
https://github.com/haschdl/pLaunchController

**Comment by dborowik** [comment]
LaunchPadMini mk2
