### ISSUE TITLE
a bit of progress

### ISSUE THREAD

**Issue by dborowik** [haschdl/pLaunchPadMini#4]
Thank you for the speedy response, a bit of progress;
the new example 3 still flags console error:
`The package “launchPadMiniClient” does not exist. You might be missing a
library.
Libraries must be installed in a folder named 'libraries' inside the
sketchbook folder (see the Preferences window).`

However I have copied and pasted some of the code in example 1 (and deleted what was not needed for the test) and I can see the RECEIVER logs, (but not the println message from the function):
`Connected to Launchpad Mini MIDI Input.
Connected to Launchpad Mini MIDI Output.
Resetting the controller...
Launchpad Mini ready!
[Receiver] Last message:-112,34,127
Pad pressed at (2,2)! Changing color...
[RECEIVER] Sending LED ON message.Location: 2,2 Note: 34 
[RECEIVER] You pressed (x,y) = (2,2)
[Receiver] Last message:-112,34,0`

Here is the Processing code I used, based on Example 1.pde
`/**
 * This examples shows how to set LED colors in the Novation Launch Pad Mini.
 * The several examples alternate on mouseClick - click anywhere on the sketch to move 
 * from example to another.
 * 
 * 
 * 26.10.2010, Half Scheidl
 * 
 *
 */

import launchPadMiniClient.*;
LaunchPadMini controller;

int example;
int examples = 7;

void setup() {
  size(800, 200);
  frameRate(10);

  try {
    controller = new LaunchPadMini(this);
    controller.LogMode = LOG_MODE.VERBOSE;
  }
  catch(Exception e) {
    println("Unfortunately we could not detect that Launch Pad MINI is connected to this computer :(");
    exit();
  }
}

void launchPadMiniPadChanged(int col, int row) {
  println(String.format("Pad changed! Column: %d Row: %d", col, row));
}`

**Comment by haschdl** [comment]
Thanks for the detailed information. I deleted my local files and tried to install from the release ZIP file and I got the same error. I made a mistake when creating the release in Github and the JAR file was missing its contents. Could you re-download and give it another try? I recommend closing Processing and deleting the current folder you might have for the library - in order words, start clean :)

**Comment by dborowik** [comment]
Thank you very much for sorting out Half!
It works fine now. 

Would it be ok for me to suggest slight improvements if you have time to look at it?

**Comment by haschdl** [comment]
Absolutely, send them on! It will probably make it more useful for others
too. If we iron out the current glitches I ask to publish it to Processing
library.

**Comment by dborowik** [comment]
Brilliant thanks!
Happy to help you test and try n contribute where i can.
I dont have many, but i guess i would had them as 'issues' for you to
categories as needed?

**Comment by haschdl** [comment]
Yes, you can do that! Submit your ideas and I will do the tagging/triaging
needed.

**Comment by haschdl** [comment]
Closing in favor of #5 #6 and #7
